spring:
  application:
    name: microservice-cards

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address : localhost